### ISSUE TITLE
User control of multiprocessing

### ISSUE THREAD

**Issue by TomGoffrey** [s-goldman/Dusty-Evolved-Star-Kit#146]
Whilst carrying out my JOSS review I wondered if there was a reason to not allow the user finer-grained control of the multiprocessing? My understanding right now is that the user can either run with a single process, or on N-1 processes, where N is the number of (logical) cores. I can think of cases where the user might want to run with an intermediate value, or indeed with N processes rather than N-1.

Is this possible?

**Comment by s-goldman** [comment]
@TomGoffrey I think that is a great idea. I can add in the option of Multiprocessing=(True, False, or number_of_core).
