### ISSUE TITLE
[Clarify] Documentation - Multiprocessing significance

### ISSUE THREAD

**Issue by Deech08** [s-goldman/Dusty-Evolved-Star-Kit#153]
As part of JOSS Review openjournals/joss-reviews#2554

From what I can gauge, multiprocessing is only used if desk fit is run on a folder with many input files. Clarification in the documentation on this would be best, letting users know that multiprocessing will only affect performance when fitting many input sets in a folder, as opposed to just make a single fit run faster.

**Comment by s-goldman** [comment]
Documentation has been added.

commit c84ce6bea9a453a3f52c2a1e0f767860ca370e33
