### ISSUE TITLE
[Docs] Testing Instructions / Guide

### ISSUE THREAD

**Issue by Deech08** [s-goldman/Dusty-Evolved-Star-Kit#160]
As part of openjournals/joss-reviews#2554

Looks like you have tests, which I'm able to run. and all pass (test_console_commands.py). But I had to dig through to find these and run. Since the repository doesn't use some kind of continuous integration (Travis CI, etc.) it would be best to include a line in the readme or a small section in the documentation that tells a user how they can run the test to make sure the package installed properly and such.

**Comment by s-goldman** [comment]
@Deech08 There is continuous integration testing done through Github actions (The link is the [python package: passing] button on the readme; [https://github.com/s-goldman/Dusty-Evolved-Star-Kit/actions](https://github.com/s-goldman/Dusty-Evolved-Star-Kit/actions)). I will make this more clear, and add some documentation about how to initiate the tests manually.

**Comment by Deech08** [comment]
ah, my fault! Thats quite clear actually so no need to add more unless you want to!
