### ISSUE TITLE
[Request] Issue Templates

### ISSUE THREAD

**Issue by Deech08** [s-goldman/Dusty-Evolved-Star-Kit#161]
As part of openjournals/joss-reviews#2554

In your docs, you have a nice page for contributing and how to do it. It would be helpful if you can make issue templates for bug reports and feature requests that list what you ask in the docs, but just lays it out within a GitHub template so its more clear and obvious for users. 

(you can do this in settings, features, issues)

**Comment by s-goldman** [comment]
Completed in commit 1d1efd5517209d69cc89961183fe5de8a78123d5
